#!/bin/sh
# Restart WDTT when WAN comes up

[ "$ACTION" = "ifup" ] || exit 0
[ "$INTERFACE" = "wan" ] || exit 0

enabled="$(uci -q get wdtt.globals.enabled 2>/dev/null)"
[ "$enabled" = "1" ] || exit 0

/etc/init.d/wdtt restart

exit 0
